version: 0.2

env:
   parameter-store:
           MONGOURL: "/amiya/mongourl"

phases:
   build:
        commands:
            - sed -i 's/localhost/'$MONGOURL'/' app.js
artifacts:
        files:
            - '**/*'
